export type AppPermission =
  | 'VIEW_DASHBOARD'
  | 'VIEW_BANKS'
  | 'MANAGE_BANKS'
  | 'VIEW_BANK_ACCOUNTS'
  | 'MANAGE_BANK_ACCOUNTS'
  | 'VIEW_BANK_INTEGRATIONS'
  | 'MANAGE_BANK_INTEGRATIONS'
  | 'VIEW_TRANSACTIONS'
  | 'EXECUTE_P2P'
  | 'EXECUTE_IMMEDIATE_CREDIT_DEBIT'
  | 'EXECUTE_VPOS'
  | 'EXECUTE_C2P'
  | 'VIEW_USERS'
  | 'MANAGE_USERS'
  | 'VIEW_API_ERROR_LOGS'
  | 'VIEW_AUDIT_LOGS'
  | 'MANAGE_SECURITY';

export type UserRole = 'ADMIN' | 'OPERADOR' | 'AUDITOR';

export const ROLE_PERMISSIONS: Record<UserRole, AppPermission[]> = {
  ADMIN: [
    'VIEW_DASHBOARD',
    'VIEW_BANKS',
    'MANAGE_BANKS',
    'VIEW_BANK_ACCOUNTS',
    'MANAGE_BANK_ACCOUNTS',
    'VIEW_BANK_INTEGRATIONS',
    'MANAGE_BANK_INTEGRATIONS',
    'VIEW_TRANSACTIONS',
    'EXECUTE_P2P',
    'EXECUTE_IMMEDIATE_CREDIT_DEBIT',
    'EXECUTE_VPOS',
    'EXECUTE_C2P',
    'VIEW_USERS',
    'MANAGE_USERS',
    'VIEW_API_ERROR_LOGS',
    'VIEW_AUDIT_LOGS',
    'MANAGE_SECURITY',
  ],
  OPERADOR: [
    'VIEW_DASHBOARD',
    'VIEW_BANKS',
    'VIEW_BANK_ACCOUNTS',
    'MANAGE_BANK_ACCOUNTS',
    'VIEW_BANK_INTEGRATIONS',
    'VIEW_TRANSACTIONS',
    'EXECUTE_P2P',
    'EXECUTE_IMMEDIATE_CREDIT_DEBIT',
    'EXECUTE_VPOS',
    'EXECUTE_C2P',
  ],
  AUDITOR: [
    'VIEW_DASHBOARD',
    'VIEW_BANKS',
    'VIEW_BANK_ACCOUNTS',
    'VIEW_BANK_INTEGRATIONS',
    'VIEW_TRANSACTIONS',
    'VIEW_API_ERROR_LOGS',
    'VIEW_AUDIT_LOGS',
  ],
};

export function getPermissionsForRole(role: UserRole): AppPermission[] {
  return ROLE_PERMISSIONS[role] ?? [];
}

